
import { E2EEncryption } from './crypto.js';

// WebRTC Configuration - using public STUN servers
const rtcConfig = {
  iceServers: [
    { urls: 'stun:stun.l.google.com:19302' },
    { urls: 'stun:stun1.l.google.com:19302' }
  ]
};

// CERTIFICATE PINNING: Server's public key (generated by generate-keys.js)
// Replace this with your actual server public key after running generate-keys.js
const PINNED_SERVER_PUBLIC_KEY = `
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3OtJyQOMJsQl0wNjQTwH
AXsdslsVE5Q9/HkhPmsxbDkscV1ZbuMmXqJpDzn/5BXFVgyPZUd8ObBMN8ITN1Hq
MFxqsDq/j99N2Lhx+zUVwTpv4M3HN93EOKdWmxIv6H222IvfTcV/03tZE4g04OG1
0LC0onIXtG/Ha31KcVDP9JEn3dcwwcPOGEFss1NegsU2lyGKLQdxgDjR3w45LKgY
FXmyy8S/S2K8tc1wnDMkJpu1Zcn/4RiO0kqg/4iWy1igBmMcIMQZNV611z2CIo5A
ViWJtXSG1fckZ7Z6HtImIVLURfLF7vy213zV57AHeET6YRoHTisnRhsGdK4BcCFP
rQIDAQAB
-----END PUBLIC KEY-----
`.trim();

// Set to false to disable certificate pinning (for development)
const ENABLE_CERTIFICATE_PINNING = false;

// E2E encryption automatically enabled in secure contexts (HTTPS/localhost)
const ENABLE_E2E_ENCRYPTION = window.isSecureContext;

class SecureMeeting {
  constructor() {
    this.ws = null;
    this.clientId = null;
    this.roomId = null;
    this.localStream = null;
    this.peers = new Map();
    this.videoEnabled = true;
    this.audioEnabled = true;
    this.crypto = new E2EEncryption();
    this.isHost = false;
    this.hostId = null;
    this.serverVerified = false;
    this.pendingMessages = [];

    this.breakouts = []; // [{ subRoomId, name, participants: [] }]

    this.init();
  }

  async init() {
    if (ENABLE_E2E_ENCRYPTION) {
      await this.crypto.generateKeyPair();
    } else {
      console.warn('⚠ E2E encryption disabled (requires HTTPS or localhost)');
    }
    this.initUI();
    this.connect();
  }

  initUI() {
    document.getElementById('createBtn').onclick = () => this.showCreateOptions();
    document.getElementById('confirmCreateBtn').onclick = () => this.confirmCreateRoom();
    document.getElementById('cancelCreateBtn').onclick = () => this.hideCreateOptions();
    document.getElementById('joinBtn').onclick = () => this.joinRoom();
    document.getElementById('submitPassphraseBtn').onclick = () => this.submitPassphrase();
    document.getElementById('leaveBtn').onclick = () => this.leaveRoom();
    document.getElementById('toggleVideo').onclick = () => this.toggleVideo();
    document.getElementById('toggleAudio').onclick = () => this.toggleAudio();
    document.getElementById('lockRoomBtn').onclick = () => this.toggleRoomLock();
    document.getElementById('generateTokenBtn').onclick = () => this.generateToken();
    document.getElementById('setPassphraseBtn').onclick = () => this.promptSetPassphrase();

    // One-time creation of local overlay (we'll reuse it)
    this.switchOverlay = null;

    const returnMainBtn = document.getElementById('returnMainBtn');
    if (returnMainBtn) returnMainBtn.onclick = () => this.returnToMain();

    const createBreakoutsBtn = document.getElementById('createBreakoutsBtn');
    if (createBreakoutsBtn) createBreakoutsBtn.onclick = () => this.createBreakouts();
  }

  showCreateOptions() {
    document.getElementById('createBtn').classList.add('hidden');
    document.getElementById('createOptions').classList.remove('hidden');
  }

  hideCreateOptions() {
    document.getElementById('createBtn').classList.remove('hidden');
    document.getElementById('createOptions').classList.add('hidden');
    document.getElementById('passphraseInput').value = '';
  }

  async confirmCreateRoom() {
    const passphrase = document.getElementById('passphraseInput').value.trim();
    this.hideCreateOptions();
    
    const createBtn = document.getElementById('createBtn');
    createBtn.disabled = true;
    createBtn.textContent = 'Starting...';
    
    try {
      await this.initLocalStream();
      
      // Hash passphrase client-side before sending
      const passphraseHash = passphrase ? await this.hashPassphrase(passphrase) : null;
      
      this.ws.send(JSON.stringify({ 
        type: 'create-room',
        passphrase: passphraseHash
      }));
    } catch (err) {
      createBtn.disabled = false;
      createBtn.textContent = 'Create Meeting';
    }
  }

  async hashPassphrase(passphrase) {
    // Use SHA-256 to hash the passphrase client-side
    const encoder = new TextEncoder();
    const data = encoder.encode(passphrase);
    const hashBuffer = await crypto.subtle.digest('SHA-256', data);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    const hashHex = hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
    return hashHex;
  }

  generateToken() {
    if (!this.isHost) return;
    this.ws.send(JSON.stringify({ type: 'generate-token' }));
  }

  promptSetPassphrase() {
    if (!this.isHost) return;
    const passphrase = prompt('Enter a passphrase for this meeting (leave empty to remove):');
    if (passphrase !== null) {
      // Hash passphrase client-side before sending
      if (passphrase.trim()) {
        this.hashPassphrase(passphrase.trim()).then(hash => {
          this.ws.send(JSON.stringify({ 
            type: 'set-passphrase',
            passphrase: hash
          }));
        });
      } else {
        // Empty passphrase means remove it
        this.ws.send(JSON.stringify({ 
          type: 'set-passphrase',
          passphrase: null
        }));
      }
    }
  }

  async submitPassphrase() {
    const passphrase = document.getElementById('joinPassphraseInput').value.trim();
    const roomInput = document.getElementById('roomInput').value.trim();
    const { roomId, token } = this.parseRoomInput(roomInput);
    
    document.getElementById('passphrasePrompt').classList.add('hidden');
    
    // Hash passphrase client-side before sending
    const passphraseHash = passphrase ? await this.hashPassphrase(passphrase) : null;
    
    this.ws.send(JSON.stringify({ 
      type: 'join-room', 
      roomId,
      passphrase: passphraseHash,
      token
    }));
  }

  parseRoomInput(input) {
    // Check if it's an invite URL with token
    const match = input.match(/([a-f0-9]+)\?token=([a-f0-9]+)/);
    if (match) {
      return { roomId: match[1], token: match[2] };
    }
    // Just a room ID
    return { roomId: input, token: null };
  }

  connect() {
    const protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
    this.ws = new WebSocket(`${protocol}//${window.location.host}`);
    
    this.ws.onopen = () => {
      console.log('WebSocket connected');
      
      // Verify server identity before allowing any operations
      if (ENABLE_CERTIFICATE_PINNING) {
        this.verifyServerIdentity();
      } else {
        console.warn('⚠ Certificate pinning disabled');
        this.serverVerified = true;
      }
    };

    this.ws.onmessage = (event) => {
      const msg = JSON.parse(event.data);
      this.handleMessage(msg);
    };

    this.ws.onerror = (error) => {
      console.error('WebSocket error:', error);
    };

    this.ws.onclose = () => {
      console.log('WebSocket closed, reconnecting...');
      this.serverVerified = false;
      setTimeout(() => this.connect(), 3000);
    };
  }

  async verifyServerIdentity() {
    try {
      console.log('🔒 Verifying server identity...');
      
      // Generate random challenge
      const challengeArray = new Uint8Array(32);
      crypto.getRandomValues(challengeArray);
      const challenge = btoa(String.fromCharCode(...challengeArray));
      
      // Store challenge for verification
      this.identityChallenge = challenge;
      
      // Send challenge to server
      this.ws.send(JSON.stringify({
        type: 'verify-server-identity',
        challenge
      }));
      
      // Set timeout for verification
      this.verificationTimeout = setTimeout(() => {
        if (!this.serverVerified) {
          console.error('❌ Server identity verification timeout');
          alert('Security Error: Could not verify server identity. Connection refused.');
          this.ws.close();
        }
      }, 5000);
      
    } catch (err) {
      console.error('Server identity verification failed:', err);
      alert('Security Error: Server identity verification failed. Connection refused.');
      this.ws.close();
    }
  }

  async handleServerIdentityVerified(signature) {
    try {
      // Import server's public key
      // Remove PEM headers and all whitespace/newlines
      const publicKeyData = PINNED_SERVER_PUBLIC_KEY
        .replace(/-----BEGIN PUBLIC KEY-----/g, '')
        .replace(/-----END PUBLIC KEY-----/g, '')
        .replace(/\s/g, '');  // Remove all whitespace including newlines
      
      const binaryKey = Uint8Array.from(atob(publicKeyData), c => c.charCodeAt(0));
      
      const publicKey = await crypto.subtle.importKey(
        'spki',
        binaryKey,
        {
          name: 'RSA-PSS',
          hash: 'SHA-256'
        },
        false,
        ['verify']
      );
      
      // Verify signature
      const signatureData = Uint8Array.from(atob(signature), c => c.charCodeAt(0));
      const challengeData = Uint8Array.from(atob(this.identityChallenge), c => c.charCodeAt(0));
      
      const verified = await crypto.subtle.verify(
        {
          name: 'RSA-PSS',
          saltLength: 32
        },
        publicKey,
        signatureData,
        challengeData
      );
      
      if (verified) {
        console.log('✓ Server identity verified successfully');
        this.serverVerified = true;
        clearTimeout(this.verificationTimeout);
        
        // Process any pending messages
        this.pendingMessages.forEach(msg => this.handleMessage(msg));
        this.pendingMessages = [];
      } else {
        throw new Error('Signature verification failed');
      }
      
    } catch (err) {
      console.error('❌ Server identity verification failed:', err);
      alert('Security Error: Server identity verification failed. This could indicate a man-in-the-middle attack. Connection refused.');
      this.ws.close();
    }
  }

  async handleMessage(msg) {
    console.log('Received message:', msg.type);
    
    // Handle server identity verification messages immediately
    if (msg.type === 'server-identity-verified') {
      await this.handleServerIdentityVerified(msg.signature);
      return;
    }
    
    if (msg.type === 'server-identity-error') {
      console.error('Server identity error:', msg.message);
      alert('Security Error: ' + msg.message);
      this.ws.close();
      return;
    }
    
    // Queue messages until server is verified
    if (ENABLE_CERTIFICATE_PINNING && !this.serverVerified) {
      console.log('Queuing message until server verified:', msg.type);
      this.pendingMessages.push(msg);
      return;
    }
    
    switch (msg.type) {
      case 'connected':
        this.clientId = msg.clientId;
        console.log('Connected with client ID:', this.clientId);
        break;
      case 'room-created':
        this.roomId = msg.roomId;
        this.subRoomId = 'main';
        this.isHost = msg.isHost;
        this.hostId = this.clientId;
        this.enterMeeting();
        if (msg.hasPassphrase) alert('Meeting created with passphrase protection');
        break;
      case 'room-joined':
        this.roomId = msg.roomId;
        this.subRoomId = 'main';
        this.isHost = msg.isHost;
        this.hostId = msg.hostId;
        this.enterMeeting();
        // Exchange public keys with all participants
        for (const peerId of msg.participants) {
          await this.exchangeKeys(peerId);
        }
        break;
      case 'peer-joined':
        await this.exchangeKeys(msg.peerId);
        break;
      case 'peer-left':
        this.removePeer(msg.peerId);
        break;
      case 'key-exchange':
        await this.handleKeyExchange(msg.fromId, msg.publicKey);
        break;
      case 'encrypted-signal':
        await this.handleEncryptedSignal(msg.fromId, msg.encrypted);
        break;
      case 'passphrase-required':
        document.getElementById('passphrasePrompt').classList.remove('hidden');
        break;
      case 'token-generated':
        this.showInviteLink(msg.inviteUrl, msg.expiresAt);
        break;
      case 'passphrase-updated':
        alert(msg.hasPassphrase ? 'Passphrase set successfully' : 'Passphrase removed');
        break;
      case 'kicked':
        alert(msg.message);
        this.leaveRoom();
        break;
      case 'mute-request':
        if (confirm(msg.message + '. Mute your microphone?')) {
          if (this.audioEnabled) {
            this.toggleAudio();
          }
        }
        break;
      case 'room-locked':
        this.updateLockStatus(true);
        break;
      case 'room-unlocked':
        this.updateLockStatus(false);
        break;
      case 'host-promoted':
        this.isHost = true;
        this.hostId = this.clientId;
        alert('You are now the host');
        this.updateHostControls();
        this.renderBreakoutsPanel();
        break;
      case 'new-host':
        this.hostId = msg.hostId;
        break;
      case 'error':
        alert(msg.message);
        // Re-enable buttons
        document.getElementById('joinBtn').disabled = false;
        document.getElementById('joinBtn').textContent = 'Join Meeting';
        break;
      case 'room-switched':
        if (msg.clientId === this.clientId || !msg.clientId) {   // only if it's me
          this.subRoomId = msg.subRoomId;
          const roomName = this.breakouts.find(r => r.subRoomId === msg.subRoomId)?.name ||
              (msg.subRoomId === 'main' ? 'Main Room' : msg.subRoomId);
          this.showSwitchFeedback(roomName);
        }
        this.roomId = msg.roomId;
        this.subRoomId = msg.subRoomId;
        this.hostId = msg.hostId;
        this.updateRoomLabel();
        this.renderBreakoutsPanel();           // ← refresh panel
        this.updateReturnMainButton();
        await this.resetPeersForRoomSwitch(msg.participants);
        break;
      case 'breakouts-state':
        this.breakouts = msg.rooms || [];
        this.updateRoomLabel();
        this.renderBreakoutsPanel();
        break;
    }
  }

  updateReturnMainButton() {
    const btn = document.getElementById('returnMainBtn');
    if (!btn) return;

    if (this.subRoomId === 'main') {
      btn.classList.add('hidden');
      // or btn.disabled = true; if you prefer disabling
    } else {
      btn.classList.remove('hidden');
      // btn.disabled = false;
    }
  }

  enterMeeting() {
    document.getElementById('lobby').classList.add('hidden');
    document.getElementById('meeting').classList.remove('hidden');
    document.getElementById('roomIdDisplay').textContent = `Meeting ID: ${this.roomId}`;

    this.addVideoStream(this.clientId, this.localStream, 'You');
    this.updateHostControls();
    this.updateRoomLabel();
    this.renderBreakoutsPanel();
  }

  updateHostControls() {
    const hostControls = document.getElementById('hostControls');
    if (this.isHost) {
      hostControls.classList.remove('hidden');
    } else {
      hostControls.classList.add('hidden');
    }
    const panel = document.getElementById('breakoutsPanel');
    if (panel) {
      if (this.isHost) panel.classList.remove('hidden');
      else panel.classList.add('hidden');
    }
    // Ensure breakout controls visibility matches host state
    const createBreakoutsBtn = document.getElementById('createBreakoutsBtn');
    if (createBreakoutsBtn) createBreakoutsBtn.disabled = !this.isHost;
  }

  updateRoomLabel() {
    const el = document.getElementById('subRoomDisplay');
    if (!el) return;

    const found = this.breakouts.find(r => r.subRoomId === this.subRoomId);
    const name = found?.name || (this.subRoomId === 'main' ? 'Main' : this.subRoomId);
    el.textContent = `Room: ${name}`;
  }

  async resetPeersForRoomSwitch(participants) {
    this.peers.forEach(pc => pc.close());
    this.peers.clear();

    if (ENABLE_E2E_ENCRYPTION) {
      for (const peerId of Array.from(this.crypto.peerPublicKeys.keys())) {
        this.crypto.removePeer(peerId);
      }
    }

    for (const node of Array.from(document.getElementById('videoGrid').children)) {
      if (node.id !== `video-${this.clientId}`) node.remove();
    }

    for (const peerId of participants) {
      await this.exchangeKeys(peerId);
    }
  }

  returnToMain() {
    if (!this.roomId) return;
    this.showSwitchFeedback('main');
    this.ws.send(JSON.stringify({ type: 'switch-breakout', subRoomId: 'main' }));
  }

  createBreakouts() {
    if (!this.isHost) return;
    const countStr = prompt('How many breakout rooms? (e.g., 2)');
    if (countStr === null) return;
    this.ws.send(JSON.stringify({ type: 'create-breakouts', count: Number(countStr) }));
  }

  assignParticipantTo(subRoomId, targetId) {
    if (!this.isHost) return;
    this.ws.send(JSON.stringify({ type: 'assign-breakout', targetId, subRoomId }));
  }

  joinSubRoom(subRoomId) {
    if (!this.roomId) return;
    this.ws.send(JSON.stringify({ type: 'switch-breakout', subRoomId }));
  }

  renderBreakoutsPanel() {
    const panel = document.getElementById('breakoutsPanel');
    const roomsEl = document.getElementById('breakoutsRooms');
    const summaryEl = document.getElementById('breakoutsSummary');
    if (!panel || !roomsEl || !summaryEl) return;

    if (!this.isHost) {
      panel.classList.add('hidden');
      return;
    }
    panel.classList.remove('hidden');

    const totalParticipants = this.breakouts.reduce((acc, r) => acc + (r.participants?.length || 0), 0);
    summaryEl.textContent = `${this.breakouts.length} rooms • ${totalParticipants} participants`;

    roomsEl.innerHTML = '';

    const roomOptions = this.breakouts.map(r => ({ subRoomId: r.subRoomId, name: r.name }));

    for (const room of this.breakouts) {
      const wrap = document.createElement('div');
      wrap.className = 'breakout-room';

      const header = document.createElement('div');
      header.className = 'breakout-room-header';

      const name = document.createElement('div');
      name.className = 'breakout-room-name';
      name.textContent = room.name || room.subRoomId;

      const actions = document.createElement('div');
      actions.className = 'breakout-room-actions';

      const joinBtn = document.createElement('button');
      joinBtn.className = 'breakout-join-btn';
      joinBtn.textContent = this.subRoomId === room.subRoomId ? 'You are here' : 'Join';
      joinBtn.disabled = this.subRoomId === room.subRoomId;
      joinBtn.onclick = () => {
        if (this.subRoomId !== room.subRoomId) {
          this.showSwitchFeedback(room.subRoomId);           // ← add this line
          this.ws.send(JSON.stringify({
            type: 'switch-breakout',
            subRoomId: room.subRoomId
          }));
        }
      };

      actions.appendChild(joinBtn);
      header.appendChild(name);
      header.appendChild(actions);
      wrap.appendChild(header);

      const participants = room.participants || [];
      if (participants.length === 0) {
        const empty = document.createElement('div');
        empty.className = 'breakout-participant';
        empty.textContent = '— empty —';
        wrap.appendChild(empty);
      } else {
        for (const pid of participants) {
          const row = document.createElement('div');
          row.className = 'breakout-participant';

          const idEl = document.createElement('div');
          idEl.className = 'breakout-participant-id';
          idEl.textContent = pid === this.clientId ? `${pid} (you)` : pid;

          const sel = document.createElement('select');
          sel.className = 'breakout-assign-select';

          for (const opt of roomOptions) {
            const o = document.createElement('option');
            o.value = opt.subRoomId;
            o.textContent = opt.name || opt.subRoomId;
            if (opt.subRoomId === room.subRoomId) o.selected = true;
            sel.appendChild(o);
          }

          sel.onchange = () => this.assignParticipantTo(sel.value, pid);

          row.appendChild(idEl);
          row.appendChild(sel);
          wrap.appendChild(row);
        }
      }

      roomsEl.appendChild(wrap);
    }
  }

  showInviteLink(inviteUrl, expiresAt) {
    const expireTime = new Date(expiresAt).toLocaleTimeString();
    
    // Construct full URL with current host
    const fullUrl = `${window.location.protocol}//${window.location.host}/${inviteUrl}`;
    
    // If accessing via localhost, show a helpful message
    const isLocalhost = window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1';
    
    let message = `Invite link (expires at ${expireTime}):\n\n${fullUrl}`;
    
    if (isLocalhost) {
      message += `\n\n⚠️ Note: This link uses 'localhost' which only works on this computer.\nFor other devices on your network, replace 'localhost' with your IP address (e.g., 192.168.x.x)`;
    }
    
    message += '\n\nShare this link with participants.';
    
    // Copy to clipboard
    navigator.clipboard.writeText(fullUrl).then(() => {
      alert(message + '\n\nLink copied to clipboard!');
    }).catch(() => {
      prompt('Invite link:', fullUrl);
    });
  }

  async createRoom() {
    const createBtn = document.getElementById('createBtn');
    createBtn.disabled = true;
    createBtn.textContent = 'Starting...';
    
    try {
      await this.initLocalStream();
      this.ws.send(JSON.stringify({ type: 'create-room' }));
    } catch (err) {
      createBtn.disabled = false;
      createBtn.textContent = 'Create Meeting';
    }
  }

  async joinRoom() {
    const roomInput = document.getElementById('roomInput').value.trim();
    if (!roomInput) {
      alert('Please enter a meeting ID or invite link');
      return;
    }
    
    const { roomId, token } = this.parseRoomInput(roomInput);
    
    // Disable button to prevent double-clicks
    const joinBtn = document.getElementById('joinBtn');
    joinBtn.disabled = true;
    joinBtn.textContent = 'Connecting...';
    
    try {
      await this.initLocalStream();
      this.ws.send(JSON.stringify({ 
        type: 'join-room', 
        roomId,
        token,
        passphrase: null
      }));
    } catch (err) {
      joinBtn.disabled = false;
      joinBtn.textContent = 'Join Meeting';
    }
  }

  async initLocalStream() {
    try {
      this.localStream = await navigator.mediaDevices.getUserMedia({
        video: { facingMode: 'user' },
        audio: {
          echoCancellation: true,
          noiseSuppression: true
        }
      });
    } catch (err) {
      console.error('Media access error:', err);
      alert(`Camera/microphone access denied: ${err.message}`);
      throw err;
    }
  }

  enterMeeting() {
    document.getElementById('lobby').classList.add('hidden');
    document.getElementById('meeting').classList.remove('hidden');
    document.getElementById('roomIdDisplay').textContent = `Meeting ID: ${this.roomId}`;
    
    this.addVideoStream(this.clientId, this.localStream, 'You');
    this.updateHostControls();
    this.updateRoomLabel();
  }

  updateRoomLabel() {
    const el = document.getElementById('subRoomDisplay');
    if (!el) return;

    const found = this.breakouts.find(r => r.subRoomId === this.subRoomId);
    const name = found?.name || (this.subRoomId === 'main' ? 'Main' : this.subRoomId);
    el.textContent = `Room: ${name}`;
  }

  async resetPeersForRoomSwitch(participants) {
    // Close all peer connections
    this.peers.forEach(pc => pc.close());
    this.peers.clear();

    // Clean up encryption keys
    if (ENABLE_E2E_ENCRYPTION) {
      // remove all peers except self
      for (const peerId of Array.from(this.crypto.peerPublicKeys.keys())) {
        this.crypto.removePeer(peerId);
      }
    }

    // Remove all remote videos
    for (const node of Array.from(document.getElementById('videoGrid').children)) {
      if (node.id !== `video-${this.clientId}`) node.remove();
    }

    // Reconnect to peers in the new room
    for (const peerId of participants) {
      await this.exchangeKeys(peerId);
    }
    this.hideSwitchFeedback();
  }

  returnToMain() {
    if (!this.roomId) return;
    this.ws.send(JSON.stringify({ type: 'switch-breakout', subRoomId: 'main' }));
  }

  createBreakouts() {
    if (!this.isHost) return;
    const countStr = prompt('How many breakout rooms? (e.g., 2)');
    if (countStr === null) return;
    this.ws.send(JSON.stringify({ type: 'create-breakouts', count: Number(countStr) }));
  }

  assignParticipantTo(subRoomId, targetId) {
    if (!this.isHost) return;
    this.ws.send(JSON.stringify({ type: 'assign-breakout', targetId, subRoomId }));
  }

  renderBreakoutsUI() {
    this.updateRoomLabel();

    // Minimal approach: reuse per-participant UI rendered in addVideoStream()
    // by updating any existing dropdown options (if present).
    for (const [peerId] of this.peers.entries()) {
      const sel = document.getElementById(`breakout-select-${peerId}`);
      if (!sel) continue;
      sel.innerHTML = '';
      for (const r of this.breakouts) {
        const opt = document.createElement('option');
        opt.value = r.subRoomId;
        opt.textContent = r.name;
        sel.appendChild(opt);
      }
    }
  }

  addVideoStream(id, stream, label) {
    if (document.getElementById(`video-${id}`)) return;

    const container = document.createElement('div');
    container.className = 'video-container';
    container.id = `video-${id}`;

    const video = document.createElement('video');
    video.srcObject = stream;
    video.autoplay = true;
    video.playsInline = true;
    if (id === this.clientId) video.muted = true;

    const labelDiv = document.createElement('div');
    labelDiv.className = 'video-label';
    labelDiv.textContent = label;

    container.appendChild(video);
    container.appendChild(labelDiv);

    if (this.isHost && id !== this.clientId) {
      const controls = document.createElement('div');
      controls.className = 'participant-controls';

      const muteBtn = document.createElement('button');
      muteBtn.textContent = '🔇';
      muteBtn.className = 'participant-btn';
      muteBtn.title = 'Request mute';
      muteBtn.onclick = () => this.muteParticipant(id);

      const kickBtn = document.createElement('button');
      kickBtn.textContent = '❌';
      kickBtn.className = 'participant-btn';
      kickBtn.title = 'Remove participant';
      kickBtn.onclick = () => this.kickParticipant(id);

      const breakoutSelect = document.createElement('select');
      breakoutSelect.id = `breakout-select-${id}`;
      breakoutSelect.className = 'breakout-select';
      breakoutSelect.title = 'Assign breakout room';
      breakoutSelect.onchange = () => this.assignParticipantTo(breakoutSelect.value, id);

      // Populate options (may be empty until breakouts-state arrives)
      for (const r of this.breakouts) {
        const opt = document.createElement('option');
        opt.value = r.subRoomId;
        opt.textContent = r.name;
        breakoutSelect.appendChild(opt);
      }

      controls.appendChild(muteBtn);
      controls.appendChild(kickBtn);
      controls.appendChild(breakoutSelect);
      container.appendChild(controls);
    }

    document.getElementById('videoGrid').appendChild(container);
  }


  updateLockStatus(locked) {
    const lockBtn = document.getElementById('lockRoomBtn');
    if (locked) {
      lockBtn.textContent = '🔒 Unlock';
      lockBtn.classList.add('locked');
    } else {
      lockBtn.textContent = '🔓 Lock';
      lockBtn.classList.remove('locked');
    }
  }

  kickParticipant(peerId) {
    if (!this.isHost) return;
    if (confirm('Remove this participant from the meeting?')) {
      this.ws.send(JSON.stringify({ type: 'kick-participant', targetId: peerId }));
    }
  }

  muteParticipant(peerId) {
    if (!this.isHost) return;
    this.ws.send(JSON.stringify({ type: 'mute-participant', targetId: peerId }));
  }

  toggleRoomLock() {
    if (!this.isHost) return;
    const lockBtn = document.getElementById('lockRoomBtn');
    const isLocked = lockBtn.classList.contains('locked');
    
    if (isLocked) {
      this.ws.send(JSON.stringify({ type: 'unlock-room' }));
    } else {
      this.ws.send(JSON.stringify({ type: 'lock-room' }));
    }
  }

  async exchangeKeys(peerId) {
    if (!ENABLE_E2E_ENCRYPTION) {
      // Skip key exchange, create peer connection directly
      this.createPeerConnection(peerId, this.clientId < peerId);
      return;
    }
    
    const publicKey = await this.crypto.exportPublicKey();
    this.ws.send(JSON.stringify({
      type: 'key-exchange',
      targetId: peerId,
      publicKey
    }));
  }

  async handleKeyExchange(fromId, publicKey) {
    if (!ENABLE_E2E_ENCRYPTION) return;
    
    await this.crypto.importPeerPublicKey(fromId, publicKey);
    
    // If we haven't sent our key yet, send it now
    if (!this.crypto.peerPublicKeys.has(fromId)) {
      await this.exchangeKeys(fromId);
    }
    
    // Now that keys are exchanged, create peer connection
    this.createPeerConnection(fromId, this.clientId < fromId);
  }

  async handleEncryptedSignal(fromId, encrypted) {
    if (!ENABLE_E2E_ENCRYPTION) return;
    
    try {
      const signal = await this.crypto.decrypt(fromId, encrypted);
      await this.handleSignal(fromId, signal);
    } catch (err) {
      console.error('Failed to decrypt signal:', err);
    }
  }

  async sendEncryptedSignal(targetId, signal) {
    if (!ENABLE_E2E_ENCRYPTION) {
      // Send unencrypted signal
      this.sendSignal(targetId, signal);
      return;
    }
    
    try {
      const encrypted = await this.crypto.encrypt(targetId, signal);
      this.ws.send(JSON.stringify({
        type: 'encrypted-signal',
        targetId,
        encrypted
      }));
    } catch (err) {
      console.error('Failed to encrypt signal:', err);
    }
  }

  createPeerConnection(peerId, initiator) {
    const pc = new RTCPeerConnection(rtcConfig);
    
    // Add local stream tracks
    this.localStream.getTracks().forEach(track => {
      pc.addTrack(track, this.localStream);
    });

    // Handle incoming stream
    pc.ontrack = (event) => {
      this.addVideoStream(peerId, event.streams[0], 'Participant');
    };

    // Handle ICE candidates
    pc.onicecandidate = (event) => {
      if (event.candidate) {
        this.sendEncryptedSignal(peerId, { candidate: event.candidate });
      }
    };

    this.peers.set(peerId, pc);

    if (initiator) {
      pc.createOffer()
        .then(offer => pc.setLocalDescription(offer))
        .then(() => this.sendEncryptedSignal(peerId, { offer: pc.localDescription }));
    }
  }

  async handleSignal(peerId, signal) {
    let pc = this.peers.get(peerId);
    
    if (!pc) {
      console.warn('Received signal before peer connection created');
      return;
    }

    if (signal.offer) {
      await pc.setRemoteDescription(new RTCSessionDescription(signal.offer));
      const answer = await pc.createAnswer();
      await pc.setLocalDescription(answer);
      this.sendEncryptedSignal(peerId, { answer: pc.localDescription });
    } else if (signal.answer) {
      await pc.setRemoteDescription(new RTCSessionDescription(signal.answer));
    } else if (signal.candidate) {
      await pc.addIceCandidate(new RTCIceCandidate(signal.candidate));
    }
  }

  sendSignal(targetId, signal) {
    this.ws.send(JSON.stringify({
      type: 'signal',
      targetId,
      signal
    }));
  }

  removePeer(peerId) {
    const pc = this.peers.get(peerId);
    if (pc) {
      pc.close();
      this.peers.delete(peerId);
    }

    // Clean up encryption keys
    this.crypto.removePeer(peerId);

    const videoElement = document.getElementById(`video-${peerId}`);
    if (videoElement) videoElement.remove();
  }

  toggleVideo() {
    this.videoEnabled = !this.videoEnabled;
    this.localStream.getVideoTracks().forEach(track => {
      track.enabled = this.videoEnabled;
    });
    document.getElementById('toggleVideo').classList.toggle('disabled');
  }

  toggleAudio() {
    this.audioEnabled = !this.audioEnabled;
    this.localStream.getAudioTracks().forEach(track => {
      track.enabled = this.audioEnabled;
    });
    document.getElementById('toggleAudio').classList.toggle('disabled');
  }

  leaveRoom() {
    // Stop all tracks
    if (this.localStream) {
      this.localStream.getTracks().forEach(track => track.stop());
    }

    // Close all peer connections
    this.peers.forEach(pc => pc.close());
    this.peers.clear();

    // Clear video grid
    document.getElementById('videoGrid').innerHTML = '';

    // Return to lobby
    document.getElementById('meeting').classList.add('hidden');
    document.getElementById('lobby').classList.remove('hidden');
    
    this.roomId = null;
    this.localStream = null;
  }
  showSwitchFeedback(targetSubRoomId) {
    const localTile = this.getLocalVideoTile();
    if (!localTile) return;

    // Find the friendly name from this.breakouts
    let roomName = 'Main Room';
    if (targetSubRoomId !== 'main') {
      const room = this.breakouts.find(r => r.subRoomId === targetSubRoomId);
      roomName = room?.name || targetSubRoomId;  // fallback to subRoomId if name missing
    }

    if (!this.switchOverlay) {
      this.switchOverlay = document.createElement('div');
      this.switchOverlay.className = 'switch-overlay';
      localTile.appendChild(this.switchOverlay);  // create once, reuse
    }

    // Update text dynamically
    this.switchOverlay.innerHTML = `
    <div class="spinner"></div>
    Moving to ${roomName}…
  `;

    // Show
    this.switchOverlay.classList.add('visible');

    // Auto-hide – shorter duration
    clearTimeout(this._switchTimeout);
    this._switchTimeout = setTimeout(() => {
      this.hideSwitchFeedback();
    }, 1500);  // ← 2 seconds; change to 1500 or 1800 if you want even quicker
  }

  hideSwitchFeedback() {
    if (this.switchOverlay) {
      this.switchOverlay.classList.remove('visible');
    }
  }

  getLocalVideoTile() {
    // Option A: if you already track your local video element
    if (this.localVideo) {
      return this.localVideo.parentElement;  // assuming video is wrapped in .video-tile
    }

    // Option B: find by data attribute or known ID/class
    return document.querySelector('.video-tile.local') ||    // ← add class="video-tile local" to your local tile in render
        document.querySelector('[data-client-id="' + this.clientId + '"]') ||
        document.getElementById('localVideoWrapper') ||    // if you have a dedicated wrapper
        document.querySelector('#videoGrid > div:first-child');  // fallback – often local is first
  }

}// end class

// Initialize app
new SecureMeeting();
